# Generated by Django 4.0.3 on 2022-03-11 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_basket_categories_products_users_delete_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.CharField(blank=1, max_length=255),
        ),
    ]
