# Generated by Django 4.0.3 on 2022-03-29 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_products_mult'),
    ]

    operations = [
        migrations.CreateModel(
            name='subCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categories')),
                ('prodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products')),
            ],
        ),
    ]
