# Generated by Django 4.0.3 on 2022-03-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_products_cat_remove_subcategories_prodid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='mult',
            field=models.FloatField(default=1.0),
        ),
    ]
