# Generated by Django 4.0.3 on 2022-04-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_products_hotshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='newsletter',
            field=models.BooleanField(default=True),
        ),
    ]
