# Generated by Django 4.0.3 on 2022-05-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_users_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
